#!/bin/bash
## |Created by mcauto_astroid                           | #
workdir=base_plan/exec/215A1/$LSB_JOBINDEX/
#BSUB -J 215A1_ch1[1-30]
#BSUB -q medium
#BSUB -r     
#BSUB -o "base_plan/exec/215A1/215A1_ch1.%I.out"
#BSUB -e "base_plan/exec/215A1/215A1_ch1.%I.err"
#BSUB -C 0 
#BSUB -n 2
#BSUB -R "rusage[mem=2500]"
#BSUB -Q "140"             

cd $workdir

cp ../../../input/215A1/run/DoseGrid_Dw.txt ./
cp ../../../input/215A1/run/IMPT_beam.txt ./
cp ../../../input/215A1/run/IMPT_patient.txt ./
cp ../../../input/215A1/run/MCAUTO_DICOM.txt ./
cp ../../../input/215A1/run/MCAUTO_DICOM_SEQUENCE.txt ./
cp ../../../input/215A1/run/plan_ch1.txt ./
time topas plan_ch1.txt.$LSB_JOBINDEX
if [ $? -eq 0 ]; then
    touch DONE.215A1_ch1
else
    touch FAIL.215A1_ch1
fi
