#ifndef __WARP_OPTIONS__
#define __WARP_OPTIONS__

enum Warp_opts_t
{
    FREE_POS_FREE_ENERGY,
    FREE_POS_RIGID_ENERGY,
    FREE_POS_RIGID_BEAMS_ENERGY,

    RIGID_POS_FREE_ENERGY,
    RIGID_POS_RIGID_ENERGY,
    RIGID_POS_RIGID_BEAMS_ENERGY,

    RIGID_BEAMS_POS_FREE_ENERGY,
    RIGID_BEAMS_POS_RIGID_ENERGY,
    RIGID_BEAMS_POS_RIGID_BEAMS_ENERGY,

    // RIGID_POS_LAYERS_FREE_ENERGY,
    // RIGID_ENERGY_LAYERS_FREE_POS,
    // RIGID_ENERGY_LAYERS_RIGID_POS_LAYERS,
};

#endif